#!/usr/bin/env bash

# Set up autograder files
#touch /autograder/submission/delete_this_file.py
cp /autograder/submission/* /autograder/source/
#rm /autograder/source/delete_this_file.py

cd /autograder/source

python3 run_tests.py
